# Server Port
server.port=8761

# Application Name
spring.application.name=eureka-server

# Eureka Client Configuration
# Since this is the server, it shouldn't register with itself or fetch its own registry
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Eureka Server Configuration
# Set wait time to 0 so the server starts advertising immediately without waiting for peers
eureka.server.wait-time-in-ms-when-sync-empty=0