spring.application.name=demo


management.endpoints.web.exposure.include=health,info 
management.info.env.enabled=true

spring.main.lazy-initialization=true

logging.level.org.springframework=warn

spring.mvc.view.prefix=/WEB-INF/jsp/
spring.mvc.view.suffix=.jsp